### PR TITLE
Add support to synchronize a DataSet to JSON format

### PR DESCRIPTION
**Pull request by peendebak**
@CumulonimbusCalvus

### CODE REVIEW

**Comment by peendebak** [comment]
@kel85uk Sure, do you have suggestions?

**Comment by kel85uk** [comment]
Something simple such as dataset_to_json.py or jsonSerializer.py? At least something different from the standard json module I guess.

**Comment by peendebak** [comment]
@kel85uk Did a rename to `json_serializer`. Thanks!

**Comment by CumulonimbusCalvus** [comment]
👍 That is nice, some improvements from QI to the lab!

**Pull request merged**
