### PR TITLE
[DEM-1043] Resolve circular dependency problem in qtt and qilib

### PR DESCRIPTION
**Pull request by ammar92**

### CODE REVIEW

**Comment by peendebak** [comment]
@ammar92 Plesae move the `qtt/adapters` to `qtt/instrument_drivers/adapters`. (in any case, not in the top level directory)

**Comment by peendebak** [comment]
@ammar92 Codacy and tests are failing

**Comment by ammar92** [comment]
> 
> 
> @ammar92 Codacy and tests are failing

Correct, that's because it depends on qilib, and the new features are not yet merged. They're awaiting to be merged in https://github.com/QuTech-Delft/qilib/pull/37

**Comment by CumulonimbusCalvus** [comment]
Taking all the blame...

**Pull request merged**
